-- 商品服务数据库初始化
-- 数据库名: cgb_product

CREATE TABLE IF NOT EXISTS `shangpin` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `mingcheng` VARCHAR(200) NOT NULL COMMENT '商品名称',
  `leixing` VARCHAR(50) DEFAULT NULL COMMENT '商品类型',
  `tupian` VARCHAR(200) DEFAULT NULL COMMENT '商品图片',
  `jieshao` TEXT DEFAULT NULL COMMENT '商品介绍',
  `tihuofangshi` VARCHAR(100) DEFAULT NULL COMMENT '提货方式',
  `kucun` INT DEFAULT 0 COMMENT '库存',
  `jiage` DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '价格',
  `yuanjia` DECIMAL(10,2) DEFAULT 0.00 COMMENT '原价',
  `status` TINYINT DEFAULT 0 COMMENT '状态 0上架 1下架',
  `userid` BIGINT DEFAULT NULL COMMENT '所属商家',
  `addtime` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updatetime` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `isdelete` TINYINT DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品表';

CREATE TABLE IF NOT EXISTS `shangpin_collection` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `userid` BIGINT NOT NULL COMMENT '用户ID',
  `shangpinid` BIGINT NOT NULL COMMENT '商品ID',
  `addtime` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updatetime` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `isdelete` TINYINT DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_product` (`userid`, `shangpinid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品收藏表';

CREATE TABLE IF NOT EXISTS `shangpin_comment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `shangpinid` BIGINT NOT NULL COMMENT '商品ID',
  `userid` BIGINT NOT NULL COMMENT '用户ID',
  `pingfen` TINYINT NOT NULL COMMENT '评分1-5',
  `pingjianeirong` TEXT DEFAULT NULL COMMENT '评价内容',
  `parentid` BIGINT DEFAULT NULL COMMENT '父评价ID',
  `addtime` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updatetime` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `isdelete` TINYINT DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品评价表';

CREATE TABLE IF NOT EXISTS `shangpin_liuyan` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `shangpinid` BIGINT NOT NULL COMMENT '商品ID',
  `userid` BIGINT NOT NULL COMMENT '用户ID',
  `liuyanneirong` TEXT DEFAULT NULL COMMENT '留言内容',
  `parentid` BIGINT DEFAULT NULL COMMENT '父留言ID',
  `addtime` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updatetime` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `isdelete` TINYINT DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品留言表';