-- 内容服务数据库初始化
-- 数据库名: cgb_content

CREATE TABLE IF NOT EXISTS `news` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL COMMENT '标题',
  `content` TEXT DEFAULT NULL COMMENT '内容',
  `picture` VARCHAR(200) DEFAULT NULL COMMENT '封面图',
  `type` VARCHAR(50) DEFAULT NULL COMMENT '类型',
  `publishtime` VARCHAR(50) DEFAULT NULL COMMENT '发布时间',
  `addtime` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updatetime` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `isdelete` TINYINT DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='社区公告表';

CREATE TABLE IF NOT EXISTS `forum` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL COMMENT '标题',
  `content` TEXT DEFAULT NULL COMMENT '内容',
  `picture` VARCHAR(200) DEFAULT NULL COMMENT '封面图',
  `parentid` VARCHAR(50) DEFAULT NULL COMMENT '父帖子ID',
  `userid` BIGINT DEFAULT NULL COMMENT '发帖用户',
  `username` VARCHAR(100) DEFAULT NULL COMMENT '用户名',
  `avatar` VARCHAR(200) DEFAULT NULL COMMENT '头像',
  `thumbsupnum` INT DEFAULT 0 COMMENT '点赞数',
  `cainixihao` INT DEFAULT 0 COMMENT '踩',
  `addtime` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updatetime` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `isdelete` TINYINT DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='论坛帖子表';

CREATE TABLE IF NOT EXISTS `messages` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `userid` BIGINT NOT NULL COMMENT '留言用户',
  `username` VARCHAR(100) DEFAULT NULL COMMENT '用户名',
  `content` TEXT DEFAULT NULL COMMENT '留言内容',
  `parentid` BIGINT DEFAULT NULL COMMENT '父留言ID',
  `replycontent` TEXT DEFAULT NULL COMMENT '回复内容',
  `addtime` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updatetime` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `isdelete` TINYINT DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='留言板表';

CREATE TABLE IF NOT EXISTS `zixun` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL COMMENT '标题',
  `content` TEXT DEFAULT NULL COMMENT '内容',
  `picture` VARCHAR(200) DEFAULT NULL COMMENT '封面图',
  `source` VARCHAR(100) DEFAULT NULL COMMENT '来源',
  `publishtime` VARCHAR(50) DEFAULT NULL COMMENT '发布时间',
  `addtime` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updatetime` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `isdelete` TINYINT DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='团购资讯表';