-- 团购评论表
CREATE TABLE IF NOT EXISTS `tuan_comment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `tuanweiid` BIGINT DEFAULT NULL COMMENT '团购ID',
  `userid` BIGINT DEFAULT NULL COMMENT '评论用户',
  `nickname` VARCHAR(100) DEFAULT NULL COMMENT '评论用户昵称',
  `content` TEXT DEFAULT NULL COMMENT '评论内容',
  `reply` TEXT DEFAULT NULL COMMENT '回复内容',
  `tablename` VARCHAR(50) DEFAULT 'tuangouxinxi' COMMENT '类型标识',
  `addtime` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updatetime` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `isdelete` TINYINT DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='团购评论表';
